"""
Project Euler Problem 2
=======================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
"""

print(4613732)


sum = 0
def fib(a, b):
	c = a + b
	if c < 4000000:
		if c % 2 == 0:
			sum += c
		
		return fib(b, c)
	return 0
	
fib(0,1)
print (sum)
